---
- name: Creating "exam" user for remote hosts
  hosts: all

  tasks:
  - name: Add exam user to all remote hosts
    user:
      name: exam
      shell: /bin/bash
      group: wheel
      append: yes

  - name: Push SSH keys to remote hosts
    authorized_key: 
      user: exam
      state: present
      key: "{{ lookup('file', '/home/exam/.ssh/id_rsa.pub') }}"

  - name: Put exam user into sudoers
    lineinfile:
      path: /etc/sudoers.d/exam
      line: 'exam ALL=(ALL) NOPASSWD: ALL' 
      state: present
      mode: 0440
      create: yes
      validate: 'visudo -cf %s'

  - name: include DIR in sudoers
    lineinfile:
      dest: /etc/sudoers
      line: "#includedir /etc/sudoers.d"
      state: present
      validate: "/usr/sbin/visudo -cf %s"  

      
